// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dailystats

import (
	"time"
)

type QueueDailyStat struct {
	ID                    int64     `json:"id"`
	QueueID               int32     `json:"queue_id"`
	QueueName             string    `json:"queue_name"`
	Date                  time.Time `json:"date"`
	TotalTicketsAvailable int32     `json:"total_tickets_available"`
	TakenTickets          int32     `json:"taken_tickets"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}
