// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dailystats

import (
	"context"
	"time"
)

const getDailyStatsByDate = `-- name: GetDailyStatsByDate :one
SELECT id, queue_id, queue_name, date, tickets_served, registered_tickets, created_at, updated_at FROM queue_daily_stats
WHERE queue_id = $1 AND date = $2
`

type GetDailyStatsByDateParams struct {
	QueueID int32     `json:"queue_id"`
	Date    time.Time `json:"date"`
}

func (q *Queries) GetDailyStatsByDate(ctx context.Context, arg GetDailyStatsByDateParams) (QueueDailyStat, error) {
	row := q.db.QueryRowContext(ctx, getDailyStatsByDate, arg.QueueID, arg.Date)
	var i QueueDailyStat
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.QueueName,
		&i.Date,
		&i.TicketsServed,
		&i.RegisteredTickets,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatsByDateRange = `-- name: GetStatsByDateRange :many
SELECT id, queue_id, queue_name, date, tickets_served, registered_tickets, created_at, updated_at FROM queue_daily_stats
WHERE queue_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date ASC
`

type GetStatsByDateRangeParams struct {
	QueueID int32     `json:"queue_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

func (q *Queries) GetStatsByDateRange(ctx context.Context, arg GetStatsByDateRangeParams) ([]QueueDailyStat, error) {
	rows, err := q.db.QueryContext(ctx, getStatsByDateRange, arg.QueueID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueDailyStat
	for rows.Next() {
		var i QueueDailyStat
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.QueueName,
			&i.Date,
			&i.TicketsServed,
			&i.RegisteredTickets,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyStats = `-- name: UpsertDailyStats :exec
INSERT INTO queue_daily_stats (queue_id, queue_name, date, tickets_served, registered_tickets, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (queue_id, date)
DO UPDATE SET
    tickets_served = EXCLUDED.tickets_served,
    registered_tickets = EXCLUDED.registered_tickets,
    queue_name = EXCLUDED.queue_name,
    updated_at = NOW()
`

type UpsertDailyStatsParams struct {
	QueueID           int32     `json:"queue_id"`
	QueueName         string    `json:"queue_name"`
	Date              time.Time `json:"date"`
	TicketsServed     int32     `json:"tickets_served"`
	RegisteredTickets int32     `json:"registered_tickets"`
}

func (q *Queries) UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyStats,
		arg.QueueID,
		arg.QueueName,
		arg.Date,
		arg.TicketsServed,
		arg.RegisteredTickets,
	)
	return err
}
