// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dailystats

import (
	"context"
)

type Querier interface {
	GetDailyStatsByDate(ctx context.Context, arg GetDailyStatsByDateParams) (QueueDailyStat, error)
	GetStatsByDateRange(ctx context.Context, arg GetStatsByDateRangeParams) ([]QueueDailyStat, error)
	UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) error
}

var _ Querier = (*Queries)(nil)
