// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dailystats

import (
	"context"
	"time"
)

const getStatsByDateRange = `-- name: GetStatsByDateRange :many
SELECT id, queue_id, queue_name, date, total_tickets_available, taken_tickets, created_at, updated_at
FROM queue_daily_stats
WHERE queue_id = $1 AND date BETWEEN $2 AND $3
ORDER BY date ASC
`

type GetStatsByDateRangeParams struct {
	QueueID int32     `json:"queue_id"`
	Date    time.Time `json:"date"`
	Date_2  time.Time `json:"date_2"`
}

func (q *Queries) GetStatsByDateRange(ctx context.Context, arg GetStatsByDateRangeParams) ([]QueueDailyStat, error) {
	rows, err := q.db.QueryContext(ctx, getStatsByDateRange, arg.QueueID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueDailyStat
	for rows.Next() {
		var i QueueDailyStat
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.QueueName,
			&i.Date,
			&i.TotalTicketsAvailable,
			&i.TakenTickets,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyStats = `-- name: UpsertDailyStats :exec
INSERT INTO queue_daily_stats (queue_id, queue_name, date, total_tickets_available, taken_tickets, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (queue_id, date)
DO UPDATE SET
    total_tickets_available = EXCLUDED.total_tickets_available,
    taken_tickets = EXCLUDED.taken_tickets,
    queue_name = EXCLUDED.queue_name,
    updated_at = NOW()
`

type UpsertDailyStatsParams struct {
	QueueID               int32     `json:"queue_id"`
	QueueName             string    `json:"queue_name"`
	Date                  time.Time `json:"date"`
	TotalTicketsAvailable int32     `json:"total_tickets_available"`
	TakenTickets          int32     `json:"taken_tickets"`
}

func (q *Queries) UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyStats,
		arg.QueueID,
		arg.QueueName,
		arg.Date,
		arg.TotalTicketsAvailable,
		arg.TakenTickets,
	)
	return err
}
