apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-monitor
spec:
  template:
    spec:
      containers:
        - name: queue-monitor
          env:
            - name: LOG_LEVEL
              value: "debug"
            - name: STATUS_CHECK_INTERVAL_SECONDS
              value: "120"
