apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: default
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: postgres-storage
  bootstrap:
    initdb:
      database: duw_stats
      owner: duw_stats_admin
      secret:
        name: postgres-external-secret
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
