apiVersion: batch/v1
kind: Job
metadata:
  name: duw-migrations-1-1-0
  namespace: default
spec:
  ttlSecondsAfterFinished: 86400
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: acrduwshared.azurecr.io/duw-migrations:1.1.0
          env:
            - name: GOOSE_DRIVER
              value: "postgres"
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  name: postgres-app-duw-stats
                  key: uri
            - name: GOOSE_COMMAND
              value: "up"
