apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-app-external-secret
  namespace: default
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical-secret-store
  refreshInterval: 1h
  target:
    name: postgres-app
    creationPolicy: Owner
    template:
      data:
        uri: "postgresql://{{ .username }}:{{ .password }}@postgres-rw:5432/duw_stats"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: /postgres/POSTGRES_USER
    - secretKey: password
      remoteRef:
        key: /postgres/POSTGRES_PASSWORD
