apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: default
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical-secret-store
  refreshInterval: 1h
  data:
    - secretKey: username
      remoteRef:
        key: /postgres/POSTGRES_USER
    - secretKey: password
      remoteRef:
        key: /postgres/POSTGRES_PASSWORD
