apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-monitor
spec:
  template:
    spec:
      containers:
        - name: queue-monitor
          env:
            - name: WORKING_HOUR_END_UTC
              value: "17"
