# Add validation for version: use regex for semantic versioning
name: Publish workflow
on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        options: [queue-monitor, telegram-bot, queue-stats-reports, duw-migrations]
        description: 'Name of the service to publish'
        required: true
      version:
        description: 'Semantic version of the service to publish'
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code
        uses: actions/checkout@v4

      - id: azure-login
        name: 'Azure login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACTION_PUBLISH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - id: login-acr
        name: 'Login to ACR using CLI to allow log in using service principal'
        shell: bash
        run: |
          az acr login --name acrduwshared
      
      - id: verify-image
        name: 'Verify image with version does not exist'
        shell: bash
        run: |
          IMAGE_NAME="acrduwshared.azurecr.io/${{ inputs.service }}:${{ inputs.version }}"
          if docker pull $IMAGE_NAME; then
            echo "❌ Image $IMAGE_NAME already exists. Exiting."
            exit 1
          else
            echo "Image $IMAGE_NAME does not exist. Proceeding with build."
          fi
      - id: get-build-config
        name: 'Get build configuration'
        shell: bash
        run: |
          if [ "${{ inputs.service }}" = "duw-migrations" ]; then
            echo "CONTEXT=./db" >> $GITHUB_OUTPUT
            echo "DOCKERFILE=./db/Dockerfile" >> $GITHUB_OUTPUT
          else
            SERVICE_NAME_TRANSFORMED=$(echo "${{ inputs.service }}" | sed 's/-//g')
            echo "CONTEXT=." >> $GITHUB_OUTPUT
            echo "DOCKERFILE=./cmd/${SERVICE_NAME_TRANSFORMED}/Dockerfile" >> $GITHUB_OUTPUT
          fi

      - id: build-push-image
        name: 'Build and push Docker image'
        uses: docker/build-push-action@v6
        with:
          context: ${{ steps.get-build-config.outputs.CONTEXT }}
          file: ${{ steps.get-build-config.outputs.DOCKERFILE }}
          push: true
          tags: |
            acrduwshared.azurecr.io/${{ inputs.service }}:${{ inputs.version }}
            acrduwshared.azurecr.io/${{ inputs.service }}:latest
      - id: create-tag
        name: Create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.service }}-${{ inputs.version }}',
              sha: context.sha
            })